const ActionNames = {
    ADD_EXPENSE: "ADD_EXPENSE",
    RED_EXPENSE: "RED_EXPENSE",
    DELETE_EXPENSE: "DELETE_EXPENSE",
    SET_BUDGET: "SET_BUDGET",
    CHG_CURRENCY: "CHG_CURRENCY",
};

export const { ADD_EXPENSE, RED_EXPENSE, DELETE_EXPENSE, SET_BUDGET, CHG_CURRENCY } = ActionNames;
